# -*- coding: utf-8 -*-
"""funcao_teste-SV_PINN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toNhnzrKAEXm4vLTnOKMauR1psRxD6KX
"""

# -*- coding: utf-8 -*-
"""
Amostra das funções de teste para as SV-PINNs em dominios de hipercubo (0,1)^d.

As funçoes de teste sao realizacoes do processo Whittle-Matern process

    Phi(xi, x) = tau * sum_k (1 + lambda_k)^{-1/2} w_k(xi) phi_k(x)

aproximado sobre o grid Omega = (0,1)^d pela solução da SPDE discretizada

    (1 - Delta_h)^{1/2} Phi^(h) = tau * W

via DST-1 (Transformada de Seno Discreta do Tipo 1)
"""
import jax
import jax.flatten_util
import jax.numpy as jnp
import jaxopt
import json
import numpy as np
import os
import time
 
from jax import random, config
 
config.update("jax_enable_x64", True)
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
 
activation_function = jax.nn.tanh

def u(x):
    """Solucao exata da EDP"""
    return x * jnp.exp(-x**2)


def rhs(x):
    """Define o lado direito da equação"""
    return (4*x**3 - 6*x) * jnp.exp(-x**2)


# ==========================================
# 1. CONFIGURAÇÕES DO DOMÍNIO E GROUND TRUTH
# ==========================================
x_lower = 0
x_upper = 1

# Geração do Ground Truth com malha de 1000 pontos
gt_file = "gt_poisson_1d.json"
if not os.path.exists(gt_file):
    raise FileNotFoundError(f"Arquivo '{gt_file}' não encontrado.")

with open(gt_file, 'r') as f:
    gt_data = json.load(f)
    
X_test = jnp.array(gt_data['X']).reshape(-1, 1)
Y_test = jnp.array(gt_data['U_true']).reshape(-1, 1)

print(f"Ground truth carregado com {X_test.shape[0]} pontos.")

# ==========================================
# 1. DST-I (orthonormal, self-inverse)
# ==========================================
def dst1_matrix(n, dtype=jnp.float64):
    """
    Matriz ortonormal DST-I (n x n), S @ S == I (self-inverse).

    Matriz para 1-dimensão. Consequencia da separabilidade da DST-1.
    Conseguimos usar a mesma matriz e aplicá-la eixo por eixo, ajustando assim
    os custos computacionais desta implementação para niveis razoáveis.

    Parametros
    --------
    n: numero de pontos de colocação

    Retorna
    --------
    S: matrix DST-I (n x n)
    """
    h = 1.0 / (n + 1)
    idx = jnp.arange(1, n + 1, dtype=dtype)
    S = jnp.sqrt(2 * h) * jnp.sin(jnp.pi * jnp.outer(idx, idx) * h)
    return S


def dst1_nd(u, S):
    """
    Aplica a DST ortonormal e d-dimensional em um tensor u, um eixo por vez.
    (autofunções do Laplaciano de Dirichlet em (0,1)^d
    sao produtos de seno em 1 dimensao, pela equacao 4.2)
    """
    out = u
    for axis in range(u.ndim):
        out = jnp.moveaxis(jnp.tensordot(S, out, axes=([1], [axis])), 0, axis)
    return out

# ==========================================
# 2. Discretised eigenvalues of the Dirichlet Laplacian (between Eq. 4.9-4.10)
# ==========================================
def discrete_eigenvalues(n, d, dtype=jnp.float64):
    """
    lambda_k^(h) do Laplaciano Discreto no grid, para o dominio no hipercubo (0,1)^d, k_j = 1..n.

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão

    Retorna
    ----------
    Autovalores discretizados
    """
    h = 1.0 / (n + 1) # tamanho do passo
    k = jnp.arange(1, n + 1, dtype=dtype)
    lam_1d = (4.0 / (h ** 2)) * (jnp.sin(jnp.pi * k * h / 2.0) ** 2)
    grids = jnp.meshgrid(*([lam_1d] * d), indexing="ij")
    return sum(grids)

# ==========================================
# 3. Sampling realisations of Phi^(h) (Eq. 4.10)
# ==========================================
def sample_test_function(key, n, d, tau=1.0, dtype=jnp.float64):
    """
    Cria uma realização da função de teste Phi^(h) no grid x^(k), k_j = 1,...,n,
    no dominio do hipercubo (0,1)^d (Eq. 4.10).

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão
    tau: fator de escala

    Retorna
    ----------
    Phi(h), função de teste
    """
    h = 1.0 / (n + 1)
    S = dst1_matrix(n, dtype=dtype)
    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)

    W = random.normal(key, (n,) * d, dtype=dtype)    # white noise on the grid
    W_hat = dst1_nd(W, S)                             # DST-I of the white noise
    Phi_hat = weight * W_hat                          # solve in spectral space
    Phi = dst1_nd(Phi_hat, S)                          # DST^{-1} = DST-I (self-inverse)
    return (h ** (-d / 2.0)) * tau * Phi


def sample_test_functions(key, n, d, N, tau=1.0, dtype=jnp.float64):
    """
    Constroi N realizações iid phi_1, ..., phi_N de Phi^(h),
    empilhadas ao longo do eixo 0, e shape (N,) + (n,)*d.

    Estas são as funções teste empiricas da perda da SV-PINN. (eq. 4.4).
    """

    # A partir da matrix S, seremos capazes de gerar a DST-1 em n-dimensões,
    # apenas aplicando a S eixo por eixo.
    S = dst1_matrix(n, dtype=dtype)

    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)
    h = 1.0 / (n + 1)
    scale = (h ** (-d / 2.0)) * tau

    keys = random.split(key, N)

    def _one(k):
        W = random.normal(k, (n,) * d, dtype=dtype)
        Phi = dst1_nd(weight * dst1_nd(W, S), S)
        return scale * Phi

    return jax.vmap(_one)(keys)

# ==========================================
# 4. Grid of collocation points x^(k) in (0,1)^d (matching the test functions)
# ==========================================
def grid_points(n, d, dtype=jnp.float64):
    h = 1.0 / (n + 1)
    coords = (jnp.arange(1, n + 1, dtype=dtype) * h,) * d
    mesh = jnp.meshgrid(*coords, indexing="ij")
    return jnp.stack(mesh, axis=-1)  # shape (n,)*d + (d,)


# ==========================================
# 1. Empirical Phi-stochastically weak norm squared (Eq. 4.4)
# ==========================================
def sv_pinn_norm_squared(residual, phi_samples):
    """
    L_{Phi^(n)}(theta) = (1/N) sum_j [ (1/N_c) sum_i R(x_c^i) phi_j(x_c^i) ]^2

    Parametros
    ----------
    residual: R(x_c^(i)) = L u_theta(x_c^(i)) - f(x_c^(i)) no grid de
              colocacao, shape (n,)*d (mesmo grid dos phi_samples).
    phi_samples: N realizacoes de Phi^(h), shape (N,) + (n,)*d
                 (saida de sample_test_functions).

    Retorna
    ----------
    Escalar, a perda empirica L_{Phi^(n)}(theta) (Eq. 4.4).
    """

    # A tupla nao contempla o eixo 0 (o range começa a partir de 1),
    # porque o eixo 0 indexa qual é a realização N da função de teste phi_j
    # Portanto, a tupla 'axes' guarda apenas os eixos dos pontos de colocação N_c
    axes = tuple(range(1, phi_samples.ndim))  # todos os eixos espaciais

    # média dos produtos internos sobre o eixo dos pontos de colocação
    inner_products = jnp.mean(residual[None, ...] * phi_samples, axis=axes)  # (N,)

    # retorna a media sobre o eixo j (o mesmo que foi ignorado na construção da tupla inicial)
    return jnp.mean(inner_products ** 2)


# ==========================================
# 3. Perda total da SV-PINN (Eq. 4.5)
# ==========================================
def sv_pinn_loss(residual_interior, phi_samples, boundary_residual=None, lam=0.0):
    """
    L_SV(theta) = L_{Phi^(n)}(theta) + lambda * L_b(theta)

    lam = 0 quando a condicao de contorno e' imposta de forma "hard"
    na arquitetura (e.g. via DAFF), como no paper.

    Parametros
    ----------
    residual_interior: R(x_c^(i)) no grid de colocacao, shape (n,)*d.
    phi_samples: realizacoes de Phi^(h), shape (N,) + (n,)*d.
    boundary_residual: u_theta(x_b) - g(x_b) nos pontos de contorno
                        (qualquer shape); None se lam = 0.
    lam: peso da penalidade de contorno.

    Retorna
    ----------
    Escalar, L_SV(theta).
    """
    L_phi = sv_pinn_norm_squared(residual_interior, phi_samples)
    if lam == 0.0 or boundary_residual is None:
        return L_phi
    L_b = jnp.mean(boundary_residual ** 2)
    return L_phi + lam * L_b


# ==========================================
# 5. ARQUITETURA DA REDE E RESÍDUO DA EDP
#    (mesma arquitetura/derivadas de pinn_poisson_1d.py; aqui devolvemos o
#    RESÍDUO BRUTO R(x) = u_xx(x) - rhs(x), pois a perda SV-PINN (Eq. 4.4)
#    precisa do resíduo ponderado pelas funções de teste, não do seu MSE)
# ==========================================
@jax.jit
def forward(x, params):
    *hidden, output = params
    for layer in hidden:
        x = activation_function(x @ layer['W'] + layer['B'])
    return x @ output['W'] + output['B']
 
 
def laplacian(f, argnum=0):
    return jax.grad(jax.grad(f, argnums=argnum), argnums=argnum)
 
 
def pde(u_fn):
    return lambda x: laplacian(f=lambda x_: jnp.sum(u_fn(x_)), argnum=0)(x)
 
 
def residual_interior(params, x_grid):
    """R(x_c^(i)) = u_xx(x_c^(i)) - rhs(x_c^(i)) no grid de colocação x_grid
    (shape (n,)), que deve coincidir com o grid usado para amostrar phi_samples."""
    def u_net(x_val):
        x_v = x_val.reshape(1, 1)
        return forward(x_v, params)[0, 0]
 
    u_xx = jax.vmap(pde(u_net))(x_grid)
    return u_xx - rhs(x_grid)
 
 
def boundary_residual(params):
    """u_theta(0) - u(0) e u_theta(1) - u(1) (condição de contorno não-homogênea)."""
    b0 = forward(jnp.array([[0.0]]), params)[0, 0] - u(jnp.array(0.0))
    b1 = forward(jnp.array([[1.0]]), params)[0, 0] - u(jnp.array(1.0))
    return jnp.array([b0, b1])


# ==========================================
# 6. CALIBRAÇÃO (E ATUALIZAÇÃO) DE LAMBDA PARA CONTORNO NÃO-HOMOGÊNEO
#    lambda = L_Phi(theta) / L_b(theta)
#    (equilibra os dois termos da perda (Eq. 4.5) nos parametros atuais;
#    recalculado periodicamente ao longo do treinamento, acompanhando theta)
# ==========================================
def compute_lambda(params, x_grid, phi_samples, eps=1e-10):
    """eps evita divisao por L_b quase-zero (observado a levar lambda a
    explodir e o treinamento a divergir quando o contorno ja' esta' bem
    ajustado mas o interior ainda nao)."""
    R = residual_interior(params, x_grid)
    L_phi = sv_pinn_norm_squared(R, phi_samples)
    L_b = jnp.mean(boundary_residual(params) ** 2)
    return L_phi / (L_b + eps)

# ==========================================
# 7. TREINAMENTO DAS SV-PINNs (SOMENTE L-BFGS, SEM ADAM)
# ==========================================
architectures = [
    [1, 1], [2, 1],
    [5, 1], [10, 1], [20, 1], [40, 1],
    [5, 5, 1], [10, 10, 1], [20, 20, 1], [40, 40, 1],
    [5, 5, 5, 1], [10, 10, 10, 1], [20, 20, 20, 1], [40, 40, 40, 1]
]
 
n_colloc = 1024            # pontos de colocação = grid da DST-I (Table A.8, caso 1D)
N_test_functions = 25000   # numero de funcoes teste amostradas (Table A.8, caso 1D)
num_runs = 3               # 3 repeticoes, como no protocolo experimental do paper (Sec. 6)
lbfgs_maxiter = 5000       # SV-PINNs treinadas por L-BFGS por 5,000 passos (Sec. 6)
tau = 1.0                  # escala fixa de Phi; o equilibrio dos termos da perda e feito via lambda
n_lambda_updates = 5       # numero de vezes que lambda e recalculado durante o treinamento
 
main_key = jax.random.PRNGKey(42)
 
# grid de colocacao x_c^(i), fixo, identico ao grid usado para amostrar phi (Sec. 4.3.1)
x_grid = grid_points(n_colloc, d=1)[:, 0]
 
for arch in architectures:
    width = [1] + arch
    arch_str = "_".join(map(str, width))
 
    print("\n" + "=" * 20)
    print(f"INICIANDO: ARQUITETURA {width} | {num_runs} EXECUÇÕES (SV-PINN, L-BFGS)")
    print("=" * 20)
 
    acc_train_lbfgs = 0.0
    acc_eval_time = 0.0
    l2_errors = []
    all_loss_trajectories = []       # (num_runs, lbfgs_maxiter), curva de treino
    all_l2_error_trajectories = []   # (num_runs, lbfgs_maxiter), curva de treino
 
    Y_nn_final = None
    params_final_flat = None
 
    # Inicializador auxiliar apenas para obter a função unflatten (estrutura fixa por arquitetura)
    initializer = jax.nn.initializers.glorot_normal()
    dummy_key = jax.random.split(main_key, len(width) - 1)
    dummy_params = []
    for k, lin, lout in zip(dummy_key, width[:-1], width[1:]):
        dummy_params.append({'W': jnp.zeros((lin, lout)), 'B': jnp.zeros((1, lout))})
 
    _, unflatten_fn = jax.flatten_util.ravel_pytree(dummy_params)
 
    @jax.jit
    def objective_lbfgs(p_flat, phi_samples_run, lam):
        # nao usa sv_pinn_loss diretamente aqui pois seu "if lam == 0.0"
        # e' um teste em Python puro, incompativel com um lam rastreado (traced)
        # pelo jit/L-BFGS quando ele varia a cada segmento; o calculo abaixo
        # e' a mesma Eq. (4.5), so' que sem esse desvio condicional.
        params = unflatten_fn(p_flat)
        R = residual_interior(params, x_grid)
        Rb = boundary_residual(params)
        L_phi = sv_pinn_norm_squared(R, phi_samples_run)
        L_b = jnp.mean(Rb ** 2)
        return L_phi + lam * L_b
 
    # lambda e' recalculado a cada 'segment_iters' passos (ver loop de treino abaixo),
    # entao o L-BFGS roda em segmentos menores em vez de um unico run de lbfgs_maxiter passos
    segment_iters = max(1, lbfgs_maxiter // n_lambda_updates)
    lbfgs = jaxopt.LBFGS(fun=objective_lbfgs, maxiter=segment_iters, history_size=50, tol=1e-12)

    # Mesma otimizacao de um segmento que `lbfgs.run` fazia, mas passo-a-passo
    # (lbfgs.init_state + lbfgs.update via jax.lax.scan) para registrar a
    # trajetoria do loss e do erro L2 relativo (contra X_test/Y_test) a cada
    # passo, necessaria para o plot da curva de treinamento.
    @jax.jit
    def lbfgs_segment_with_trajectory(p_flat, phi_samples_run, lam):
        init_state = lbfgs.init_state(p_flat, phi_samples_run=phi_samples_run, lam=lam)

        def step_fn(carry, _):
            p, state = carry
            p, state = lbfgs.update(p, state, phi_samples_run=phi_samples_run, lam=lam)
            params_ = unflatten_fn(p)
            Y_nn_step = forward(X_test, params_)
            l2_err = jnp.linalg.norm(Y_nn_step - Y_test) / jnp.linalg.norm(Y_test)
            return (p, state), (state.value, l2_err)

        (p_final, state_final), (loss_traj, err_traj) = jax.lax.scan(
            step_fn, (p_flat, init_state), xs=None, length=segment_iters)
        return p_final, state_final, loss_traj, err_traj
 
    for run in range(num_runs):
        print(f"\n--- Run {run + 1}/{num_runs} ---")
 
        # 1. Inicializar parâmetros com uma semente diferente por run
        run_key = jax.random.fold_in(main_key, run)
        layer_keys = jax.random.split(run_key, len(width) - 1)
        params = []
        for k, lin, lout in zip(layer_keys, width[:-1], width[1:]):
            W = initializer(k, (lin, lout), jnp.float64)
            B = initializer(k, (1, lout), jnp.float64)
            params.append({'W': W, 'B': B})
 
        params_flat, _ = jax.flatten_util.ravel_pytree(params)
 
        # 2. Amostrar as N funções teste (fixas durante todo o treino desta run, Sec. 4.5)
        run_key, sub = jax.random.split(run_key)
        phi_samples_run = sample_test_functions(sub, n=n_colloc, d=1, N=N_test_functions, tau=tau)
 
        # 3. Lambda inicial: lambda = L_Phi(theta_0) / L_b(theta_0)
        lam = compute_lambda(params, x_grid, phi_samples_run)
 
        # 4. Otimização via L-BFGS em segmentos, recalculando lambda entre eles
        t_start_lbfgs = time.perf_counter()
        loss_traj_segments = []
        err_traj_segments = []
        for seg in range(n_lambda_updates):
            params_flat, state, loss_traj_seg, err_traj_seg = lbfgs_segment_with_trajectory(
                params_flat, phi_samples_run, lam)
            loss_traj_segments.append(np.asarray(loss_traj_seg))
            err_traj_segments.append(np.asarray(err_traj_seg))
            params = unflatten_fn(params_flat)
            lam = compute_lambda(params, x_grid, phi_samples_run)  # atualiza lambda com os params atuais
        params = params.copy()
        loss_lbfgs = objective_lbfgs(params_flat, phi_samples_run, lam).block_until_ready()
        t_lbfgs = time.perf_counter() - t_start_lbfgs

        loss_trajectory_run = np.concatenate(loss_traj_segments)       # (lbfgs_maxiter,)
        l2_error_trajectory_run = np.concatenate(err_traj_segments)    # (lbfgs_maxiter,)
        all_loss_trajectories.append(loss_trajectory_run)
        all_l2_error_trajectories.append(l2_error_trajectory_run)
 
        acc_train_lbfgs += t_lbfgs
        print(f"L-BFGS concluído em {t_lbfgs:.2f}s | lambda final = {float(lam):.4e} | Loss: {loss_lbfgs:.8e}")
 
        # 5. Avaliação nos pontos Ground Truth
        t_start_eval = time.perf_counter()
        Y_nn = forward(X_test, params).reshape(X_test.shape)
        Y_nn.block_until_ready()
        t_eval = time.perf_counter() - t_start_eval
        acc_eval_time += t_eval
 
        norma_erro = jnp.linalg.norm(Y_nn - Y_test)
        norma_exata = jnp.linalg.norm(Y_test)
        rel_l2_error = float(norma_erro / norma_exata)
        l2_errors.append(rel_l2_error)
        print(f"Erro L2 Relativo (Run {run + 1}): {rel_l2_error:.8e}")
 
        if run == num_runs - 1:
            Y_nn_final = np.asarray(Y_nn)
            params_final_flat = np.asarray(params_flat)
 
    avg_train_lbfgs = float(acc_train_lbfgs / num_runs)
    avg_eval_time = float(acc_eval_time / num_runs)
    avg_rel_l2 = float(np.mean(l2_errors))
    median_rel_l2 = float(np.median(l2_errors))
 
    print("\n" + "-" * 20)
    print(f"RESUMO DAS MÉDIAS ({num_runs} RUNS)")
    print(f"Erro L2 Relativo Médio: {avg_rel_l2:.8e}")
    print(f"Tempo Médio Treino L-BFGS: {avg_train_lbfgs:.3f}s")
    print(f"Tempo Médio Avaliação: {avg_eval_time:.5f}s")
    print("-" * 20)
 
    results = {
        'architecture': width,
        'num_hidden_layers': len(width) - 1,
        'method': 'SV-PINN (L-BFGS)',
        'n_colloc': n_colloc,
        'n_test_functions': N_test_functions,
        'lbfgs_maxiter': lbfgs_maxiter,
        'num_runs_avg': num_runs,
        'error_relativo_medio': avg_rel_l2,
        'error_relativo_mediana': median_rel_l2,
        'time_training_lbfgs': avg_train_lbfgs,
        'time_evaluation': avg_eval_time,
        'num_params': int(len(params_final_flat))
    }

    nome_arquivo = f'dados_svpinn_1d_{arch_str}.json'
    with open(nome_arquivo, 'w') as f:
        json.dump(results, f, indent=4)

    points = {
        'x': X_test.flatten().tolist(),
        'y_nn': Y_nn_final.tolist(),
        'network_weights': params_final_flat.tolist()
    }

    nome_arquivo = f'pontos_svpinn_1d_{arch_str}.json'
    with open(nome_arquivo, 'w') as f:
        json.dump(points, f, indent=4)

    # Curva de treinamento: erro L2 relativo e loss a cada passo de L-BFGS,
    # para cada uma das `num_runs` execucoes.
    all_loss_trajectories = np.stack(all_loss_trajectories, axis=0)        # (num_runs, lbfgs_maxiter)
    all_l2_error_trajectories = np.stack(all_l2_error_trajectories, axis=0)

    training_curve = {
        'architecture': width,
        'method': 'SV-PINN (L-BFGS)',
        'n_colloc': n_colloc,
        'n_test_functions': N_test_functions,
        'lbfgs_maxiter': lbfgs_maxiter,
        'num_runs': num_runs,
        'steps': list(range(1, lbfgs_maxiter + 1)),
        'l2_relative_error_per_run': all_l2_error_trajectories.tolist(),
        'loss_per_run': all_loss_trajectories.tolist(),
        'l2_relative_error_mean': all_l2_error_trajectories.mean(axis=0).tolist(),
        'l2_relative_error_std': all_l2_error_trajectories.std(axis=0).tolist(),
    }

    nome_arquivo = f'curva_treino_svpinn_1d_{arch_str}.json'
    with open(nome_arquivo, 'w') as f:
        json.dump(training_curve, f, indent=4)

    print(f"Dados salvos como: {nome_arquivo}\n")