# -*- coding: utf-8 -*-
"""funcao_teste-SV_PINN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toNhnzrKAEXm4vLTnOKMauR1psRxD6KX
"""

# -*- coding: utf-8 -*-
"""
Amostra das funções de teste para as SV-PINNs em dominios de hipercubo (0,1)^d.

As funçoes de teste sao realizacoes do processo Whittle-Matern process

    Phi(xi, x) = tau * sum_k (1 + lambda_k)^{-1/2} w_k(xi) phi_k(x)

aproximado sobre o grid Omega = (0,1)^d pela solução da SPDE discretizada

    (1 - Delta_h)^{1/2} Phi^(h) = tau * W

via DST-1 (Transformada de Seno Discreta do Tipo 1)
"""
import jax
import jax.flatten_util
import jax.numpy as jnp
import jaxopt
import json
import numpy as np
import os
import time
 
from jax import random, config
 
config.update("jax_enable_x64", True)
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
 
activation_function = jax.nn.tanh

def u(x, y):
    """Solucao exata da EDP"""
    return x ** 2 *(x - 1) ** 2 * y * (y - 1)**2


def rhs(x, y):
    """Define o lado direito da equação"""
    return 2 * (x**4 * (3*y - 2) + x**3 * (4 - 6*y) + x**2 * (6*y**3 - 12*y**2 + 9*y - 2)
                - 6*x*(y - 1)**2 * y + (y - 1)**2 * y)


# ==========================================
# 1. CONFIGURAÇÕES DO DOMÍNIO E GROUND TRUTH
# ==========================================
x_lower = 0
x_upper = 1

# Geração do Ground Truth com malha de 1000 pontos
gt_file = "gt_poisson_2d.json"
if not os.path.exists(gt_file):
    raise FileNotFoundError(f"Arquivo '{gt_file}' não encontrado.")

with open(gt_file, 'r') as f:
    gt_data = json.load(f)
    
X_mesh_gt = jnp.array(gt_data['X'])
Y_mesh_gt = jnp.array(gt_data['Y'])
U_true_gt = jnp.array(gt_data['U_true'])

print(f"Ground truth carregado. Shape da malha de avaliação: {X_mesh_gt.shape}")

# ==========================================
# 1. DST-I (orthonormal, self-inverse)
# ==========================================
def dst1_matrix(n, dtype=jnp.float64):
    """
    Matriz ortonormal DST-I (n x n), S @ S == I (self-inverse).

    Matriz para 1-dimensão. Consequencia da separabilidade da DST-1.
    Conseguimos usar a mesma matriz e aplicá-la eixo por eixo, ajustando assim
    os custos computacionais desta implementação para niveis razoáveis.

    Parametros
    --------
    n: numero de pontos de colocação

    Retorna
    --------
    S: matrix DST-I (n x n)
    """
    h = 1.0 / (n + 1)
    idx = jnp.arange(1, n + 1, dtype=dtype)
    S = jnp.sqrt(2 * h) * jnp.sin(jnp.pi * jnp.outer(idx, idx) * h)
    return S


def dst1_nd(u, S):
    """
    Aplica a DST ortonormal e d-dimensional em um tensor u, um eixo por vez.
    (autofunções do Laplaciano de Dirichlet em (0,1)^d
    sao produtos de seno em 1 dimensao, pela equacao 4.2)
    """
    out = u
    for axis in range(u.ndim):
        out = jnp.moveaxis(jnp.tensordot(S, out, axes=([1], [axis])), 0, axis)
    return out

# ==========================================
# 2. Discretised eigenvalues of the Dirichlet Laplacian (between Eq. 4.9-4.10)
# ==========================================
def discrete_eigenvalues(n, d, dtype=jnp.float64):
    """
    lambda_k^(h) do Laplaciano Discreto no grid, para o dominio no hipercubo (0,1)^d, k_j = 1..n.

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão

    Retorna
    ----------
    Autovalores discretizados
    """
    h = 1.0 / (n + 1) # tamanho do passo
    k = jnp.arange(1, n + 1, dtype=dtype)
    lam_1d = (4.0 / (h ** 2)) * (jnp.sin(jnp.pi * k * h / 2.0) ** 2)
    grids = jnp.meshgrid(*([lam_1d] * d), indexing="ij")
    return sum(grids)

# ==========================================
# 3. Sampling realisations of Phi^(h) (Eq. 4.10)
# ==========================================
def sample_test_function(key, n, d, tau=1.0, dtype=jnp.float64):
    """
    Cria uma realização da função de teste Phi^(h) no grid x^(k), k_j = 1,...,n,
    no dominio do hipercubo (0,1)^d (Eq. 4.10).

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão
    tau: fator de escala

    Retorna
    ----------
    Phi(h), função de teste
    """
    h = 1.0 / (n + 1)
    S = dst1_matrix(n, dtype=dtype)
    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)

    W = random.normal(key, (n,) * d, dtype=dtype)    # white noise on the grid
    W_hat = dst1_nd(W, S)                             # DST-I of the white noise
    Phi_hat = weight * W_hat                          # solve in spectral space
    Phi = dst1_nd(Phi_hat, S)                          # DST^{-1} = DST-I (self-inverse)
    return (h ** (-d / 2.0)) * tau * Phi


def sample_test_functions(key, n, d, N, tau=1.0, dtype=jnp.float64):
    """
    Constroi N realizações iid phi_1, ..., phi_N de Phi^(h),
    empilhadas ao longo do eixo 0, e shape (N,) + (n,)*d.

    Estas são as funções teste empiricas da perda da SV-PINN. (eq. 4.4).
    """

    # A partir da matrix S, seremos capazes de gerar a DST-1 em n-dimensões,
    # apenas aplicando a S eixo por eixo.
    S = dst1_matrix(n, dtype=dtype)

    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)
    h = 1.0 / (n + 1)
    scale = (h ** (-d / 2.0)) * tau

    keys = random.split(key, N)

    def _one(k):
        W = random.normal(k, (n,) * d, dtype=dtype)
        Phi = dst1_nd(weight * dst1_nd(W, S), S)
        return scale * Phi

    return jax.vmap(_one)(keys)

# ==========================================
# 4. Grid of collocation points x^(k) in (0,1)^d (matching the test functions)
# ==========================================
def grid_points(n, d, dtype=jnp.float64):
    h = 1.0 / (n + 1)
    coords = (jnp.arange(1, n + 1, dtype=dtype) * h,) * d
    mesh = jnp.meshgrid(*coords, indexing="ij")
    return jnp.stack(mesh, axis=-1)  # shape (n,)*d + (d,)


# ==========================================
# 1. Empirical Phi-stochastically weak norm squared (Eq. 4.4)
# ==========================================
def sv_pinn_norm_squared(residual, phi_samples):
    """
    L_{Phi^(n)}(theta) = (1/N) sum_j [ (1/N_c) sum_i R(x_c^i) phi_j(x_c^i) ]^2

    Parametros
    ----------
    residual: R(x_c^(i)) = L u_theta(x_c^(i)) - f(x_c^(i)) no grid de
              colocacao, shape (n,)*d (mesmo grid dos phi_samples).
    phi_samples: N realizacoes de Phi^(h), shape (N,) + (n,)*d
                 (saida de sample_test_functions).

    Retorna
    ----------
    Escalar, a perda empirica L_{Phi^(n)}(theta) (Eq. 4.4).
    """

    # A tupla nao contempla o eixo 0 (o range começa a partir de 1),
    # porque o eixo 0 indexa qual é a realização N da função de teste phi_j
    # Portanto, a tupla 'axes' guarda apenas os eixos dos pontos de colocação N_c
    axes = tuple(range(1, phi_samples.ndim))  # todos os eixos espaciais

    # média dos produtos internos sobre o eixo dos pontos de colocação
    inner_products = jnp.mean(residual[None, ...] * phi_samples, axis=axes)  # (N,)

    # retorna a media sobre o eixo j (o mesmo que foi ignorado na construção da tupla inicial)
    return jnp.mean(inner_products ** 2)


# ==========================================
# 3. Perda total da SV-PINN (Eq. 4.5)
# ==========================================
def sv_pinn_loss(residual_interior, phi_samples, boundary_residual=None, lam=0.0):
    """
    L_SV(theta) = L_{Phi^(n)}(theta) + lambda * L_b(theta)

    lam = 0 quando a condicao de contorno e' imposta de forma "hard"
    na arquitetura (e.g. via DAFF), como no paper.

    Parametros
    ----------
    residual_interior: R(x_c^(i)) no grid de colocacao, shape (n,)*d.
    phi_samples: realizacoes de Phi^(h), shape (N,) + (n,)*d.
    boundary_residual: u_theta(x_b) - g(x_b) nos pontos de contorno
                        (qualquer shape); None se lam = 0.
    lam: peso da penalidade de contorno.

    Retorna
    ----------
    Escalar, L_SV(theta).
    """
    L_phi = sv_pinn_norm_squared(residual_interior, phi_samples)
    if lam == 0.0 or boundary_residual is None:
        return L_phi
    L_b = jnp.mean(boundary_residual ** 2)
    return L_phi + lam * L_b


# ==========================================
# 5. ARQUITETURA DA REDE E RESÍDUO DA EDP (2D)
#    (mesma arquitetura/derivadas de pinn_poisson_2d.py; aqui devolvemos o
#    RESÍDUO BRUTO R(x, y) = Delta u_theta(x, y) - rhs(x, y), pois a perda
#    SV-PINN (Eq. 4.4) precisa do resíduo ponderado pelas funções de teste,
#    e não do seu MSE como na PINN básica)
# ==========================================
@jax.jit
def forward(xy, params):
    x = xy
    *hidden, output = params
    for layer in hidden:
        x = activation_function(x @ layer['W'] + layer['B'])
    return x @ output['W'] + output['B']


def u_net(x, y, params):
    xy = jnp.array([[x, y]])
    return forward(xy, params)[0, 0]


def laplacian_u(x, y, params):
    u_xx = jax.grad(jax.grad(lambda x_: u_net(x_, y, params), 0), 0)(x)
    u_yy = jax.grad(jax.grad(lambda y_: u_net(x, y_, params), 0), 0)(y)
    return u_xx + u_yy


def du_dx(x, y, params): return jax.grad(lambda x_: u_net(x_, y, params), 0)(x)
def du_dy(x, y, params): return jax.grad(lambda y_: u_net(x, y_, params), 0)(y)


def residual_interior(params, xy_grid):
    """R(x_c^(i)) = Delta u_theta(x_c^(i)) - rhs(x_c^(i)) no grid de colocação
    xy_grid (shape (n, n, 2), saída de grid_points(n, d=2)), que deve coincidir
    com o grid espacial usado para amostrar phi_samples (shape (N, n, n))."""
    shape = xy_grid.shape[:-1]  # (n, n)
    pts = xy_grid.reshape(-1, 2)

    def residual(pt):
        x, y = pt[0], pt[1]
        return laplacian_u(x, y, params) - rhs(x, y)

    R = jax.vmap(residual)(pts)
    return R.reshape(shape)


# ==========================================
# 5.1. CONDIÇÕES DE CONTORNO (Eq. (7) da imagem em anexo, todas homogêneas)
#    d_n u(0, y) = 0, y em [0, 1]      -> du_dx(0, y)
#    d_n u(1, y) = 0, y em [0, 1]      -> du_dx(1, y)
#    u(x, 0)     = 0, x em [0, 1]      -> u_net(x, 0)
#    d_n u(x, 1) = 0, x em [0, 1]      -> du_dy(x, 1)
#    Pontos de contorno fixos (uma vez, análogos ao N_g de pinn_poisson_2d.py),
#    já que aqui não há necessidade de re-amostrá-los a cada passo.
# ==========================================
n_boundary = 250
y_boundary = jnp.linspace(0.0, 1.0, n_boundary, dtype=jnp.float64)
x_boundary = jnp.linspace(0.0, 1.0, n_boundary, dtype=jnp.float64)


def boundary_residual(params):
    """Resíduos brutos (não ao quadrado) das quatro condições de contorno,
    concatenados em um único vetor 1D."""
    b_x0 = jax.vmap(lambda y: du_dx(0.0, y, params))(y_boundary)
    b_x1 = jax.vmap(lambda y: du_dx(1.0, y, params))(y_boundary)
    b_y0 = jax.vmap(lambda x: u_net(x, 0.0, params))(x_boundary)
    b_y1 = jax.vmap(lambda x: du_dy(x, 1.0, params))(x_boundary)
    return jnp.concatenate([b_x0, b_x1, b_y0, b_y1])


# ==========================================
# 6. CALIBRAÇÃO DE LAMBDA (Eq. 6.1 do paper)
#    lambda = L_Phi(theta) / L_b(theta)
#    (equilibra os dois termos da perda (Eq. 4.5) nos parâmetros atuais;
#    recalculado periodicamente ao longo do treinamento, acompanhando theta)
# ==========================================
def compute_lambda(params, xy_grid, phi_samples, eps=1e-10):
    """eps evita divisão por L_b quase-zero (observado a levar lambda a
    explodir e o treinamento a divergir quando o contorno já está bem
    ajustado mas o interior ainda não)."""
    R = residual_interior(params, xy_grid)
    L_phi = sv_pinn_norm_squared(R, phi_samples)
    L_b = jnp.mean(boundary_residual(params) ** 2)
    return L_phi / (L_b + eps)


# ==========================================
# 7. TREINAMENTO DAS SV-PINNs (SOMENTE L-BFGS, SEM ADAM)
#    Mesmas arquiteturas de pinn_poisson_2d.py (entrada 2D), mas treinadas
#    minimizando a perda estocasticamente fraca (Eq. 4.5) em vez da perda
#    forte (MSE do resíduo) da PINN básica.
# ==========================================
architectures = [
    [20, 1], [60, 1],
    [20, 20, 1], [60, 60, 1],
    [20, 20, 20, 1], [60, 60, 60, 1],
    [20, 20, 20, 20, 1], [60, 60, 60, 60, 1],
    [20, 20, 20, 20, 20, 1], [60, 60, 60, 60, 60, 1],
    [120, 120, 120, 120, 120, 1]
]

n_colloc = 264              # pontos de colocação por eixo -> grid n_colloc x n_colloc (DST-I 2D)
N_test_functions = 25000    # número de funções teste amostradas (Phi^(h))
num_runs = 3               # repetições, como no protocolo experimental do paper (Sec. 6)
lbfgs_maxiter = 5000        # SV-PINNs treinadas por L-BFGS (Sec. 6)
tau = 1.0                  # escala fixa de Phi; o equilíbrio dos termos da perda é feito via lambda
n_lambda_updates = 5        # número de vezes que lambda é recalculado durante o treinamento

main_key = jax.random.PRNGKey(42)

# grid de colocação x_c^(i), fixo, idêntico ao grid usado para amostrar phi (Sec. 4.3.1)
xy_grid = grid_points(n_colloc, d=2)  # shape (n_colloc, n_colloc, 2)

for arch in architectures:
    width = [2] + arch  # adiciona a dimensão de entrada (2)
    arch_str = "_".join(map(str, width))

    print("\n" + "=" * 50)
    print(f"INICIANDO: ARQUITETURA {width} | {num_runs} EXECUÇÕES (SV-PINN 2D, L-BFGS)")
    print("=" * 50)

    acc_train_lbfgs = 0.0
    acc_eval_time = 0.0
    l2_errors = []

    U_nn_final = None
    params_final_flat = None

    # Inicializador auxiliar apenas para obter a função unflatten (estrutura fixa por arquitetura)
    initializer = jax.nn.initializers.glorot_normal()
    dummy_key = jax.random.split(main_key, len(width) - 1)
    dummy_params = []
    for k, lin, lout in zip(dummy_key, width[:-1], width[1:]):
        dummy_params.append({'W': jnp.zeros((lin, lout), dtype=jnp.float64),
                              'B': jnp.zeros((1, lout), dtype=jnp.float64)})

    _, unflatten_fn = jax.flatten_util.ravel_pytree(dummy_params)

    @jax.jit
    def objective_lbfgs(p_flat, phi_samples_run, lam):
        # não usa sv_pinn_loss diretamente aqui pois seu "if lam == 0.0"
        # é um teste em Python puro, incompatível com um lam rastreado (traced)
        # pelo jit/L-BFGS quando ele varia a cada segmento; o cálculo abaixo
        # é a mesma Eq. (4.5), só que sem esse desvio condicional.
        params = unflatten_fn(p_flat)
        R = residual_interior(params, xy_grid)
        Rb = boundary_residual(params)
        L_phi = sv_pinn_norm_squared(R, phi_samples_run)
        L_b = jnp.mean(Rb ** 2)
        return L_phi + lam * L_b

    # lambda é recalculado a cada 'segment_iters' passos (ver loop de treino abaixo),
    # então o L-BFGS roda em segmentos menores em vez de um único run de lbfgs_maxiter passos
    segment_iters = max(1, lbfgs_maxiter // n_lambda_updates)
    lbfgs = jaxopt.LBFGS(
        fun=objective_lbfgs, maxiter=segment_iters, history_size=200, tol=1e-9, linesearch='zoom'
    )

    for run in range(num_runs):
        print(f"\n--- Run {run + 1}/{num_runs} ---")

        # 1. Inicializar parâmetros com uma semente diferente por run
        run_key = jax.random.fold_in(main_key, run)
        layer_keys = jax.random.split(run_key, len(width) - 1)
        params = []
        for k, lin, lout in zip(layer_keys, width[:-1], width[1:]):
            W = initializer(k, (lin, lout), jnp.float64)
            B = initializer(k, (1, lout), jnp.float64)
            params.append({'W': W, 'B': B})

        params_flat, _ = jax.flatten_util.ravel_pytree(params)

        # 2. Amostrar as N funções teste (fixas durante todo o treino desta run, Sec. 4.5)
        run_key, sub = jax.random.split(run_key)
        phi_samples_run = sample_test_functions(sub, n=n_colloc, d=2, N=N_test_functions, tau=tau)

        # 3. Lambda inicial: lambda = L_Phi(theta_0) / L_b(theta_0)
        lam = compute_lambda(params, xy_grid, phi_samples_run)

        # 4. Otimização via L-BFGS em segmentos, recalculando lambda entre eles
        t_start_lbfgs = time.perf_counter()
        for seg in range(n_lambda_updates):
            params_flat, state = lbfgs.run(params_flat, phi_samples_run=phi_samples_run, lam=lam)
            params = unflatten_fn(params_flat)
            lam = compute_lambda(params, xy_grid, phi_samples_run)  # atualiza lambda com os params atuais
        params = params.copy()
        loss_lbfgs = objective_lbfgs(params_flat, phi_samples_run, lam).block_until_ready()
        t_lbfgs = time.perf_counter() - t_start_lbfgs

        acc_train_lbfgs += t_lbfgs
        print(f"L-BFGS concluído em {t_lbfgs:.2f}s | lambda final = {float(lam):.4e} | Loss: {loss_lbfgs:.8e}")

        # 5. Avaliação nos pontos Ground Truth
        t_start_eval = time.perf_counter()
        xy_points = jnp.stack([X_mesh_gt.ravel(), Y_mesh_gt.ravel()], axis=-1)
        u_nn_flat = forward(xy_points, params)
        u_nn = u_nn_flat.reshape(X_mesh_gt.shape)
        u_nn.block_until_ready()
        t_eval = time.perf_counter() - t_start_eval
        acc_eval_time += t_eval

        norma_erro = jnp.linalg.norm(u_nn - U_true_gt)
        norma_exata = jnp.linalg.norm(U_true_gt)
        rel_l2_error = float(norma_erro / norma_exata)
        l2_errors.append(rel_l2_error)
        print(f"Erro L2 Relativo (Run {run + 1}): {rel_l2_error:.8e}")

        if run == num_runs - 1:
            U_nn_final = np.asarray(u_nn)
            params_final_flat = np.asarray(params_flat)

    avg_train_lbfgs = float(acc_train_lbfgs / num_runs)
    avg_eval_time = float(acc_eval_time / num_runs)
    avg_rel_l2 = float(np.mean(l2_errors))
    median_rel_l2 = float(np.median(l2_errors))

    print("\n" + "-" * 30)
    print(f"RESUMO DAS MÉDIAS ({num_runs} RUNS) - ARQUITETURA {width}")
    print(f"Erro L2 Relativo Médio: {avg_rel_l2:.8e}")
    print(f"Tempo Médio Treino L-BFGS: {avg_train_lbfgs:.3f}s")
    print(f"Tempo Médio Avaliação: {avg_eval_time:.5f}s")
    print("-" * 30)

    results = {
        'architecture': width,
        'num_hidden_layers': len(width) - 1,
        'method': 'SV-PINN (L-BFGS)',
        'n_colloc': n_colloc,
        'n_test_functions': N_test_functions,
        'lbfgs_maxiter': lbfgs_maxiter,
        'num_runs_avg': num_runs,
        'error_relativo_medio': avg_rel_l2,
        'error_relativo_mediana': median_rel_l2,
        'time_training_lbfgs': avg_train_lbfgs,
        'time_evaluation': avg_eval_time,
        'num_params': int(len(params_final_flat)),
    }

    nome_arquivo = f'dados_svpinn_2d_{arch_str}.json'
    with open(nome_arquivo, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=4)
    
    points = {
        'x': np.asarray(X_mesh_gt[0, :]).tolist(),
        'y': np.asarray(Y_mesh_gt[:, 0]).tolist(),
        'y_nn': np.asarray(U_nn_final).tolist(),
        'network_weights': params_final_flat.tolist()
    }

    nome_arquivo = f'pontos_svpinn_2d_{arch_str}.json'
    with open(nome_arquivo, 'w') as f:
        json.dump(points, f, indent=4)

    print(f"Dados salvos como: {nome_arquivo}\n")