# -*- coding: utf-8 -*-
"""funcao_teste-SV_PINN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toNhnzrKAEXm4vLTnOKMauR1psRxD6KX
"""

# -*- coding: utf-8 -*-
"""
Amostra das funções de teste para as SV-PINNs em dominios de hipercubo (0,1)^d.

As funçoes de teste sao realizacoes do processo Whittle-Matern process

    Phi(xi, x) = tau * sum_k (1 + lambda_k)^{-1/2} w_k(xi) phi_k(x)

aproximado sobre o grid Omega = (0,1)^d pela solução da SPDE discretizada

    (1 - Delta_h)^{1/2} Phi^(h) = tau * W

via DST-1 (Transformada de Seno Discreta do Tipo 1)
"""
import matplotlib.pyplot as plt
import jax
import jax.numpy as jnp
from jax import random, config

config.update("jax_enable_x64", True)

# ==========================================
# 1. DST-I (orthonormal, self-inverse)
# ==========================================
def dst1_matrix(n, dtype=jnp.float64):
    """
    Matriz ortonormal DST-I (n x n), S @ S == I (self-inverse).

    Matriz para 1-dimensão. Consequencia da separabilidade da DST-1.
    Conseguimos usar a mesma matriz e aplicá-la eixo por eixo, ajustando assim
    os custos computacionais desta implementação para niveis razoáveis.

    Parametros
    --------
    n: numero de pontos de colocação

    Retorna
    --------
    S: matrix DST-I (n x n)
    """
    h = 1.0 / (n + 1)
    idx = jnp.arange(1, n + 1, dtype=dtype)
    S = jnp.sqrt(2 * h) * jnp.sin(jnp.pi * jnp.outer(idx, idx) * h)
    return S


def dst1_nd(u, S):
    """
    Aplica a DST ortonormal e d-dimensional em um tensor u, um eixo por vez.
    (autofunções do Laplaciano de Dirichlet em (0,1)^d
    sao produtos de seno em 1 dimensao, pela equacao 4.2)
    """
    out = u
    for axis in range(u.ndim):
        out = jnp.moveaxis(jnp.tensordot(S, out, axes=([1], [axis])), 0, axis)
    return out

# ==========================================
# 2. Discretised eigenvalues of the Dirichlet Laplacian (between Eq. 4.9-4.10)
# ==========================================
def discrete_eigenvalues(n, d, dtype=jnp.float64):
    """
    lambda_k^(h) do Laplaciano Discreto no grid, para o dominio no hipercubo (0,1)^d, k_j = 1..n.

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão

    Retorna
    ----------
    Autovalores discretizados
    """
    h = 1.0 / (n + 1) # tamanho do passo
    k = jnp.arange(1, n + 1, dtype=dtype)
    lam_1d = (4.0 / (h ** 2)) * (jnp.sin(jnp.pi * k * h / 2.0) ** 2)
    grids = jnp.meshgrid(*([lam_1d] * d), indexing="ij")
    return sum(grids)

# ==========================================
# 3. Sampling realisations of Phi^(h) (Eq. 4.10)
# ==========================================
def sample_test_function(key, n, d, tau=1.0, dtype=jnp.float64):
    """
    Cria uma realização da função de teste Phi^(h) no grid x^(k), k_j = 1,...,n,
    no dominio do hipercubo (0,1)^d (Eq. 4.10).

    Parametros
    ----------
    n: numero de pontos de colocação
    d: dimensão
    tau: fator de escala

    Retorna
    ----------
    Phi(h), função de teste
    """
    h = 1.0 / (n + 1)
    S = dst1_matrix(n, dtype=dtype)
    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)

    W = random.normal(key, (n,) * d, dtype=dtype)    # white noise on the grid
    W_hat = dst1_nd(W, S)                             # DST-I of the white noise
    Phi_hat = weight * W_hat                          # solve in spectral space
    Phi = dst1_nd(Phi_hat, S)                          # DST^{-1} = DST-I (self-inverse)
    return (h ** (-d / 2.0)) * tau * Phi


def sample_test_functions(key, n, d, N, tau=1.0, dtype=jnp.float64):
    """
    Constroi N realizações iid phi_1, ..., phi_N de Phi^(h),
    empilhadas ao longo do eixo 0, e shape (N,) + (n,)*d.

    Estas são as funções teste empiricas da perda da SV-PINN. (eq. 4.4).
    """

    # A partir da matrix S, seremos capazes de gerar a DST-1 em n-dimensões,
    # apenas aplicando a S eixo por eixo.
    S = dst1_matrix(n, dtype=dtype)

    lam_k = discrete_eigenvalues(n, d, dtype=dtype)
    weight = (1.0 + lam_k) ** (-0.5)
    h = 1.0 / (n + 1)
    scale = (h ** (-d / 2.0)) * tau

    keys = random.split(key, N)

    def _one(k):
        W = random.normal(k, (n,) * d, dtype=dtype)
        Phi = dst1_nd(weight * dst1_nd(W, S), S)
        return scale * Phi

    return jax.vmap(_one)(keys)

# ==========================================
# 4. Grid of collocation points x^(k) in (0,1)^d (matching the test functions)
# ==========================================
def grid_points(n, d, dtype=jnp.float64):
    h = 1.0 / (n + 1)
    coords = (jnp.arange(1, n + 1, dtype=dtype) * h,) * d
    mesh = jnp.meshgrid(*coords, indexing="ij")
    return jnp.stack(mesh, axis=-1)  # shape (n,)*d + (d,)


# ==========================================
# 1. Empirical Phi-stochastically weak norm squared (Eq. 4.4)
# ==========================================
def sv_pinn_norm_squared(residual, phi_samples):
    """
    L_{Phi^(n)}(theta) = (1/N) sum_j [ (1/N_c) sum_i R(x_c^i) phi_j(x_c^i) ]^2

    Parametros
    ----------
    residual: R(x_c^(i)) = L u_theta(x_c^(i)) - f(x_c^(i)) no grid de
              colocacao, shape (n,)*d (mesmo grid dos phi_samples).
    phi_samples: N realizacoes de Phi^(h), shape (N,) + (n,)*d
                 (saida de sample_test_functions).

    Retorna
    ----------
    Escalar, a perda empirica L_{Phi^(n)}(theta) (Eq. 4.4).
    """

    # A tupla nao contempla o eixo 0 (o range começa a partir de 1),
    # porque o eixo 0 indexa qual é a realização N da função de teste phi_j
    # Portanto, a tupla 'axes' guarda apenas os eixos dos pontos de colocação N_c
    axes = tuple(range(1, phi_samples.ndim))  # todos os eixos espaciais

    # média dos produtos internos sobre o eixo dos pontos de colocação
    inner_products = jnp.mean(residual[None, ...] * phi_samples, axis=axes)  # (N,)

    # retorna a media sobre o eixo j (o mesmo que foi ignorado na construção da tupla inicial)
    return jnp.mean(inner_products ** 2)


# ==========================================
# 3. Perda total da SV-PINN (Eq. 4.5)
# ==========================================
def sv_pinn_loss(residual_interior, phi_samples, boundary_residual=None, lam=0.0):
    """
    L_SV(theta) = L_{Phi^(n)}(theta) + lambda * L_b(theta)

    lam = 0 quando a condicao de contorno e' imposta de forma "hard"
    na arquitetura (e.g. via DAFF), como no paper.

    Parametros
    ----------
    residual_interior: R(x_c^(i)) no grid de colocacao, shape (n,)*d.
    phi_samples: realizacoes de Phi^(h), shape (N,) + (n,)*d.
    boundary_residual: u_theta(x_b) - g(x_b) nos pontos de contorno
                        (qualquer shape); None se lam = 0.
    lam: peso da penalidade de contorno.

    Retorna
    ----------
    Escalar, L_SV(theta).
    """
    L_phi = sv_pinn_norm_squared(residual_interior, phi_samples)
    if lam == 0.0 or boundary_residual is None:
        return L_phi
    L_b = jnp.mean(boundary_residual ** 2)
    return L_phi + lam * L_b


if __name__ == "__main__":

    key = random.PRNGKey(0)
    n, d, N = 20, 2, 500

    key, sub = random.split(key)
    phi_samples = sample_test_functions(sub, n=n, d=d, N=N, tau=1.0)

    key, sub = random.split(key)
    residual = random.normal(sub, (n,) * d)

    L_direct = sv_pinn_norm_squared(residual, phi_samples)

    print("L_Phi (Eq. 4.4)      :", float(L_direct))