# -*- coding: utf-8 -*-
"""pinn-poisson-1d.ipynb

Automatically generated by Colab.
"""
import os
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"

# !pip install jaxopt # Descomente essa linha se estiver rodando no Google Colab pela primeira vez

import matplotlib.pyplot as plt
import math
import numpy as np
import time

import jax
import jax.numpy as jnp
import optax
import jaxopt

from jax import random

activation_function = jax.nn.tanh # defines tanh as activation function

def u(x):
  """Exact solution of the PDE"""
  return x * jnp.exp(-x**2)

def rhs(x):
  """Defines the right hand side of the equation"""
  return (4*x**3 - 6*x) * jnp.exp(-x**2)

# Domain of x
x_lower = 0
x_upper = 1

n  = 256
key_x = jax.random.PRNGKey(136)
key_y = jax.random.PRNGKey(871)

X = jax.random.uniform(
    key=key_x, shape=(n, 1),
    minval=x_lower, maxval=x_upper
)
X_test = jnp.linspace(x_lower, x_upper, 1000).reshape((1000, 1))
Y_test = X_test * jnp.exp(-X_test**2)

# hyperparameters
width = [1] + 3*[5] + [1]
learning_rate = 1e-4
b1 = 0.9
b2 = 0.999
eps = 1e-08
eps_root = 0.0

initializer = jax.nn.initializers.glorot_normal() # Glorot initialization
key    = jax.random.split(jax.random.PRNGKey(136), len(width) - 1)
params = list()

for key, lin, lout in zip(key, width[:-1], width[1:]):
  W = initializer(key, (lin, lout), jnp.float32)
  B = initializer(key, (1, lout)  , jnp.float32)
  params.append({'W': W, 'B': B})

#Initilize optimizer
optimizer = optax.adam(learning_rate, b1, b2, eps, eps_root)
opt_state = optimizer.init(params)

# Define function for forward pass
@jax.jit #Just in time compilation
def forward(x, params):
  *hidden, output = params
  for layer in hidden:
    x = activation_function(x @ layer['W'] + layer['B'])

  return x @ output['W'] + output['B']

def laplacian(f, argnum=0):
  """Defines laplacian using `jax.grad`"""
  return jax.grad(jax.grad(f, argnums=argnum), argnums=argnum)

def pde(u):
  """Defines the PDE"""
  uxx = lambda x: laplacian(f=lambda x: jnp.sum(u(x)), argnum=0)(x)
  return uxx

def MSE(pred, true):
  """Mean squared error"""
  return jnp.mean((pred - true) ** 2)

def loss_interior(x, params):
  """Find the loss in the domain of the function"""

  def u_net(x_val):
    """Calcula u(x) da rede neural"""
    x = x_val.reshape(1, 1)
    return forward(x, params)[0, 0]

  # Vetorizamos a operação
  laplacian_u = jax.vmap(pde(u_net))(x.flatten())

  # Voltamos o resultado para o formato original (N, 1) para calcular o erro
  u_xx = laplacian_u.reshape(-1, 1)
  return MSE(u_xx, rhs(x))

@jax.jit
def loss_function(params, x):
  pde_loss = loss_interior(x, params)

  bc_0 = MSE(forward(jnp.array([[0.0]]), params), 0.0)
  bc_1 = MSE(forward(jnp.array([[1.0]]), params), jnp.exp(-1.0))

  boundary_loss = bc_0 + bc_1

  return pde_loss + boundary_loss

#Define the gradient function
grad_loss = jax.jit(jax.grad(loss_function, 0))

#Define update function
@jax.jit
def update(opt_state, params, x):
    #Compute gradient
    grads = grad_loss(params, x)
    #Calculate parameters updates
    updates, opt_state = optimizer.update(grads, opt_state)
    #Update parameters
    params = optax.apply_updates(params, updates)
    #Return state of optmizer and updated parameters
    return opt_state, params


# ===== TREINAMENTO COM ADAM =====
epochs = 15000
print("="*70)
print("TREINAMENTO COM ADAM")
print("="*70)
print("Iniciando treinamento...")
t_start_train = time.time()
for e in range(epochs):
  #Update optimizer state and parameters
  opt_state, params = update(opt_state, params, X)

  if e % 1000 == 0:
    elapsed = time.time() - t_start_train
    print(f"{elapsed:.2f}s | Epoch {e:<6}: emp. loss {loss_function(params, X):.12f}")

loss_adam = loss_function(params, X).block_until_ready()
train_time_adam = time.time() - t_start_train

print(f"Treinamento Adam concluído em {train_time_adam:.2f}s")
print(f"Loss Adam: {loss_adam:.12f}\n")


# ===== REFINAMENTO COM L-BFGS (JAXOpt) =====
print("="*70)
print("REFINAMENTO COM L-BFGS (JAXOpt)")
print("="*70)
print("Iniciando refinamento...")

# Flatten params para o vetor 1D
params_flat, unflatten_fn = jax.flatten_util.ravel_pytree(params)

# Função objetivo para o JAXOpt
@jax.jit
def objective_lbfgs(params_flat):
    params_unflat = unflatten_fn(params_flat)
    return loss_function(params_unflat, X)

t0_lbfgs = time.time()

# Configurar o otimizador L-BFGS
lbfgs = jaxopt.LBFGS(
    fun=objective_lbfgs,
    maxiter=20000,
    history_size=50,
    tol=1e-8
)

# Executar a otimização
params_final_flat, state = lbfgs.run(params_flat)
elapsed_lbfgs = time.time() - t0_lbfgs

# Extrair e remontar os parâmetros otimizados
params = unflatten_fn(params_final_flat)

loss_lbfgs = state.error
num_iters = state.iter_num

print(f"L-BFGS concluído em {elapsed_lbfgs:.3f}s")
print(f"Loss após L-BFGS: {loss_lbfgs:.12f}")
print(f"Número de iterações L-BFGS: {num_iters}")
print("="*70 + "\n")


# ===== AVALIAÇÃO =====
t_start_eval = time.time()
Y_nn = forward(X_test.reshape((1000, 1)), params).reshape(X_test.shape)
Y_nn.block_until_ready()
eval_time = time.time() - t_start_eval

print(f"Avaliação concluída em {eval_time:.4f}s")

norma_erro = jnp.linalg.norm(Y_nn - Y_test)
norma_exata = jnp.linalg.norm(Y_test)
rel_l2_error = norma_erro / norma_exata

print(f"Erro L2 Relativo: {rel_l2_error:.8e}")

# ===== PLOTS =====
plt.plot(X_test, Y_test, '-', color='blue', markersize=0.5, label='Exact solution')
plt.plot(X_test, Y_nn, '--', color='red', markersize=0.5, label=f'PINN {width}')

plt.legend(loc='best')
plt.show()

print(f"Train loss final {loss_function(params, X)}")
print(f"Test loss final {loss_function(params, X_test)}")

# Cálculo do erro absoluto
errors = jnp.abs(Y_test - Y_nn)

plt.tight_layout()
plt.show()

# ===== CONTAR PARÂMETROS =====
params_flat_final, _ = jax.flatten_util.ravel_pytree(params)
num_params = len(params_flat_final)
num_hidden_layers = len(width) - 2

# ===== SALVAR RESULTADOS =====
results = {
    'architecture': width,
    'num_hidden_layers': int(num_hidden_layers),
    'epochs_adam': epochs,
    'error_relativo': float(rel_l2_error),
    'time_training': float(train_time_adam),
    'time_training_w_lbfgs': float(train_time_adam + elapsed_lbfgs),
    'time_evaluation': float(eval_time),
    'num_params': int(num_params),
    'y_nn': np.asarray(Y_nn),
    'network_weights': np.asarray(params_flat_final)
}

# Salvando com um nome que identifique a rede
nome_arquivo = f'dados_pinn_lbfgs_1d_{width}.npz'
np.savez_compressed(nome_arquivo, **results)

print(f"\nDados salvos com sucesso no arquivo '{nome_arquivo}'!")