# -*- coding: utf-8 -*-
"""pinn-poisson-1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFDGUYjlNE8mLj0vV20PK7uRAPesBvHi
"""

import jax
import jax.numpy as jnp
import optax
from jax import random

import matplotlib.pyplot as plt
import math
import time

activation_function = jax.nn.tanh # defines tanh as activation function

laplacian = jax.grad(jax.grad)

def u(x):
  return x * jnp.exp(-x**2)

def pde(u):
  uxx = lambda x: laplacian(lambda x: jnp.sum(u(x)), 0)(x)
  return uxx

# domain of x
x_lower = 0
x_upper = 1

n  = 100
sd = 0.1 # standard deviation
key_x = jax.random.PRNGKey(136)
key_y = jax.random.PRNGKey(871)

X = jax.random.uniform(
    key=key_x, shape=(n, 1),
    minval=x_lower, maxval=x_upper
)
Y = X * jnp.exp(-X**2) + sd * jax.random.normal(key=key_y, shape=(n, 1))
XY = jnp.append(X, Y, 1)
X_test = jnp.linspace(0, 1, 1000).reshape((1000, 1))
Y_test = X_test * jnp.exp(-X_test**2)
XY_test = jnp.append(X_test, Y_test, 1)
plt.plot(X, Y, '.', color='red', markersize=7)
plt.plot(X_test, Y_test, '-', color='blue')
plt.show()

# hyperparameters
width = [1] + 2*[20] + [1]
lr = 0.001
b1 = 0.9
b2 = 0.999
eps = 1e-08
eps_root = 0.0
epochs = 50000

initializer = jax.nn.initializers.glorot_normal() # Glorot initialization
key    = jax.random.split(jax.random.PRNGKey(136), len(width) - 1)
params = list()

for key, lin, lout in zip(key, width[:-1], width[1:]):
  W = initializer(key, (lin, lout), jnp.float32)
  B = initializer(key, (1, lout)  , jnp.float32)
  params.append({'W': W, 'B': B})

# Define function for forward pass
@jax.jit #Just in time compilation
def forward(x, params):
  *hidden, output = params
  for layer in hidden:
    x = activation_function(x @ layer['W'] + layer['B'])

  return x @ output['W'] + output['B']

def MSE(pred, true):
  return (pred - true) ** 2

@jax.jit
def loss_function(params, xy):
  return jnp.mean(
      MSE(
          forward(xy[:,0].reshape((xy.shape[0],1)), params),
          xy[:,1].reshape((xy.shape[0],1))
      )
  )

#Initilize optimizer
optimizer = optax.adam(lr, b1, b2, eps, eps_root)
opt_state = optimizer.init(params)

#Define the gradient function
grad_loss = jax.jit(jax.grad(loss_function, 0))

#Define update function
@jax.jit
def update(opt_state, params, xy):
    #Compute gradient
    grads = grad_loss(params, xy)
    #Calculate parameters updates
    updates, opt_state = optimizer.update(grads, opt_state)
    #Update parameters
    params = optax.apply_updates(params, updates)
    #Return state of optmizer and updated parameters
    return opt_state, params

Y_nn = []
for i in range(10):
  #Epochs
  t0 = time.time()
  for e in range(epochs):
    #Update optimizer state and parameters
    opt_state, params = update(opt_state, params, XY)
    if e % 10000 == 0:
      elapsed_time = f"{time.time() - t0:.2f}s"
      print(f"{elapsed_time:<6} | Epoch {e:<6}: empirical loss {loss_function(params, XY):.12f}")

  elapsed_time = f"{time.time() - t0:.2f}s"
  print(f"{elapsed_time:<6} | Epoch {e:<6}: empirical loss {loss_function(params, XY):12f}")

  Y_nn.append(forward(X_test.reshape((1000, 1)), params).reshape(X_test.shape))

# Y_nn = forward(X_test.reshape((1000, 1)), params).reshape(X_test.shape)
plt.plot(X, Y, 'o', color='red')
plt.plot(X_test, Y_test, '-', color='blue', markersize=0.5)
for i in range(len(Y_nn)):
  plt.plot(X_test, Y_nn[i], '--', markersize=0.5, label=f'PINN {i}')

plt.legend(loc='best')
plt.show()

print(f"Train loss {loss_function(params, XY)}")
print(f"Test loss {loss_function(params, XY_test)}")

# Cálculo do erro absoluto de forma vetorizada (mais rápido que o loop for)
Y_nn = jnp.array(Y_nn)
errors = jnp.mean(jnp.abs(Y_test - Y_nn), axis=0)

# Cria uma figura com 1 linha e 2 colunas para os gráficos
fig, ax = plt.subplots(1, 1, figsize=(7, 5))

# Gráfico 2: Escala Logarítmica
ax.plot(X_test, errors, '-', color='red')
ax.set_title('Erro Absoluto (Escala Logarítmica)')
ax.set_xlabel('x')
ax.set_ylabel('u(x)')
ax.set_yscale('log') # Transforma o eixo Y em escala logarítmica
ax.grid(True, which="both", linestyle='--', alpha=0.7)

# Ajusta o layout para evitar sobreposição e plota
plt.tight_layout()
plt.show()

import numpy as np

y_nn_salvar = np.asarray(Y_nn)
np.savez_compressed('dados_pinn.npz', y_nn=y_nn_salvar)

print("Dados salvos com sucesso no arquivo 'dados_pinn.npz'!")

